language: crystal
script:
  - crystal spec
  - crystal tool format src/ spec/ --check
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: awscr-s3
  on:
    branch: master
  local_dir: docs
